version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - proxy_network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    ports:
      - "8080:8080"
    networks:
      - proxy_network
    depends_on:
      - backend

networks:
  proxy_network:
    driver: bridge