version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & daphne -b 0.0.0.0 -p 8001 filtering_service.asgi:application"]
    volumes:
      - .:/app
    ports:
      - '8000:8000'
      - '8001:8001'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    volumes:
      - ./proxy_server:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'